import { Button } from "@/components/common/Button";
import { Header } from "@/components/layout/Header/Header";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Button variant="secondary">Test</Button>
    </div>
  );
};

export default Home;
