import { ArticlesPreviewPage } from "@/components/Article/ArticlesPreviewPage";
import { Header } from "@/components/layout/Header/Header";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="bg-gray-100 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ArticlesPreviewPage />
    </div>
  );
};

export default Home;
