import { ArticlesPreviewPage } from "@/components/Article/ArticlesPreviewPage";
import { PopularBlogs } from "@/components/Blogs/PopularBlogs";
import { Header } from "@/components/layout/Header/Header";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="bg-gray-100 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex gap-4 justify-between items-start mx-auto px-3 p-offset py-4 w-full">
        <ArticlesPreviewPage />
        <PopularBlogs />
      </div>
    </div>
  );
};

export default Home;
